package main

import (
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	_ "myfashion/internal/common/httpx/docs" // swagger docs (generated by swag)

	"github.com/go-chi/chi/v5"
	httpSwagger "github.com/swaggo/http-swagger"
	"gorm.io/gorm"

	"myfashion/internal/common/config"
	"myfashion/internal/common/db"
	"myfashion/internal/common/httpx"

	addressm "myfashion/internal/modules/address"
	authm "myfashion/internal/modules/auth"
	cartm "myfashion/internal/modules/cart"
	catalogm "myfashion/internal/modules/catalog"
	orderm "myfashion/internal/modules/order"
	profilem "myfashion/internal/modules/profile"
	promotionm "myfashion/internal/modules/promotion"
)

// @title MyFashion API
// @version 1.0
// @description Auth (local, Google) + Profile (customer/shop) + Catalog
// @BasePath /api/v1
// @schemes http
// @securityDefinitions.apikey Bearer
// @in header
// @name Authorization
func main() {
	cfg := config.Load()
	gdb := db.Open(cfg.DB_DSN)

	// Kiểm tra nếu có tham số migrate
	if len(os.Args) > 1 && os.Args[1] == "migrate" {
		log.Println("Running migrations...")
		runMigrations(gdb)
		log.Println("Migrations completed successfully!")
		return
	}

	runMigrations(gdb)

	r := chi.NewRouter()
	for _, mw := range httpx.Middlewares() {
		r.Use(mw)
	}

	// Serve static files for product images
	workDir, _ := os.Getwd()
	filesDir := http.Dir(filepath.Join(workDir, "uploads"))
	FileServer(r, "/uploads", filesDir)

	r.Get("/healthz", func(w http.ResponseWriter, _ *http.Request) { w.Write([]byte("ok")) })
	r.Get("/swagger/*", httpSwagger.WrapHandler)

	api := chi.NewRouter()
	authm.RegisterRoutes(api, cfg, gdb)
	profilem.RegisterRoutes(api, cfg, gdb)
	catalogm.RegisterRoutes(api, cfg, gdb)          // Register catalog routes
	cartm.RegisterRoutes(api, cfg, gdb)             // Register cart routes
	addressm.RegisterRoutes(api, cfg, gdb)          // Register address routes
	orderm.RegisterRoutes(api, gdb, cfg.JWT_Secret) // Register order routes
	promotionm.RegisterRoutes(api, cfg, gdb)        // Register promotion routes
	r.Mount("/api/v1", api)

	log.Printf("listening on :%s", cfg.Port)
	log.Fatal(http.ListenAndServe(":"+cfg.Port, r))
}

func runMigrations(db *gorm.DB) {
	if err := authm.Migrate(db); err != nil {
		log.Fatal(err)
	}
	if err := profilem.Migrate(db); err != nil {
		log.Fatal(err)
	}
	if err := catalogm.Migrate(db); err != nil {
		log.Fatal(err)
	}
	if err := cartm.Migrate(db); err != nil {
		log.Fatal(err)
	}
	if err := addressm.Migrate(db); err != nil {
		log.Fatal(err)
	}
	if err := orderm.Migrate(db); err != nil {
		log.Fatal(err)
	}
	if err := promotionm.Migrate(db); err != nil {
		log.Fatal(err)
	}
}

// FileServer conveniently sets up a http.FileServer handler to serve
// static files from a http.FileSystem.
func FileServer(r chi.Router, path string, root http.FileSystem) {
	if strings.ContainsAny(path, ":*") {
		panic("FileServer does not permit URL parameters.")
	}

	if path != "/" && path[len(path)-1] != '/' {
		r.Get(path, http.RedirectHandler(path+"/", 301).ServeHTTP)
		path += "/"
	}
	path += "*"

	r.Get(path, func(w http.ResponseWriter, r *http.Request) {
		rctx := chi.RouteContext(r.Context())
		pathPrefix := strings.TrimSuffix(rctx.RoutePattern(), "*")
		fs := http.StripPrefix(pathPrefix, http.FileServer(root))
		fs.ServeHTTP(w, r)
	})
}
