package main

import (
	"log"
	"net/http"
	"os"

	_ "myfashion/internal/common/httpx/docs" // swagger docs (generated by swag)

	"github.com/go-chi/chi/v5"
	httpSwagger "github.com/swaggo/http-swagger"
	"gorm.io/gorm"

	"myfashion/internal/common/config"
	"myfashion/internal/common/db"
	"myfashion/internal/common/httpx"

	authm "myfashion/internal/modules/auth"
	authrepo "myfashion/internal/modules/auth"
	profilem "myfashion/internal/modules/profile"
	profilerepo "myfashion/internal/modules/profile"
)

// @title MyFashion API
// @version 1.0
// @description Auth (local, Google) + Profile (customer/shop)
// @BasePath /api/v1
// @schemes http
// @securityDefinitions.apikey Bearer
// @in header
// @name Authorization
func main() {
	cfg := config.Load()
	gdb := db.Open(cfg.DB_DSN)

	// Kiểm tra nếu có tham số migrate
	if len(os.Args) > 1 && os.Args[1] == "migrate" {
		log.Println("Running migrations...")
		runMigrations(gdb)
		log.Println("Migrations completed successfully!")
		return
	}

	runMigrations(gdb)

	r := chi.NewRouter()
	for _, mw := range httpx.Middlewares() {
		r.Use(mw)
	}

	r.Get("/healthz", func(w http.ResponseWriter, _ *http.Request) { w.Write([]byte("ok")) })
	r.Get("/swagger/*", httpSwagger.WrapHandler)

	api := chi.NewRouter()
	authm.RegisterRoutes(api, cfg, gdb)
	profilem.RegisterRoutes(api, cfg, gdb)
	r.Mount("/api/v1", api)

	log.Printf("listening on :%s", cfg.Port)
	log.Fatal(http.ListenAndServe(":"+cfg.Port, r))
}

func runMigrations(db *gorm.DB) {
	if err := authrepo.Migrate(db); err != nil {
		log.Fatal(err)
	}
	if err := profilerepo.Migrate(db); err != nil {
		log.Fatal(err)
	}
}
