package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	_ "myfashion/internal/common/httpx/docs" // swagger docs (generated by swag)

	"github.com/go-chi/chi/v5"
	httpSwagger "github.com/swaggo/http-swagger"
	"gorm.io/gorm"

	"myfashion/internal/common/config"
	"myfashion/internal/common/db"
	"myfashion/internal/common/httpx"

	addressm "myfashion/internal/modules/address"
	adminm "myfashion/internal/modules/admin"
	adminRepos "myfashion/internal/modules/admin/repositories"
	authm "myfashion/internal/modules/auth"
	"myfashion/internal/modules/auth/repositories"
	"myfashion/internal/modules/auth/services"
	cartm "myfashion/internal/modules/cart"
	catalogm "myfashion/internal/modules/catalog"
	notificationm "myfashion/internal/modules/notification"
	orderm "myfashion/internal/modules/order"
	paymentm "myfashion/internal/modules/payment"
	profilem "myfashion/internal/modules/profile"
	promotionm "myfashion/internal/modules/promotion"
	promoRepos "myfashion/internal/modules/promotion/repositories"
	catalogRepos "myfashion/internal/modules/catalog/repositories"
)

// @title MyFashion API
// @version 1.0
// @description Auth (local, Google) + Profile (customer/shop) + Catalog
// @BasePath /api/v1
// @schemes https http
// @securityDefinitions.apikey Bearer
// @in header
// @name Authorization
func main() {
	cfg := config.Load()
	gdb := db.Open(cfg.DB_DSN)

	// Kiểm tra nếu có tham số migrate
	if len(os.Args) > 1 && os.Args[1] == "migrate" {
		log.Println("Running migrations...")
		runMigrations(gdb)
		log.Println("Migrations completed successfully!")
		return
	}

	runMigrations(gdb)

	// Khởi tạo blacklist repository và cleanup service
	blacklistRepo := repositories.NewBlacklistedTokenRepository(gdb)
	cleanupService := services.NewCleanupService(blacklistRepo)

	// User status checker (for immediate account disable)
	userStatusChecker := adminRepos.NewUserStatusRepository(gdb)

	// Chạy cleanup scheduler trong background (cleanup mỗi 1 giờ)
	ctx := context.Background()
	go cleanupService.StartCleanupScheduler(ctx, time.Hour)

	// Similarity recompute scheduler (CF cache) mỗi 1 giờ, topK=50
	similarityRepo := catalogRepos.NewProductSimilarityRepository(gdb)
	go startSimilarityScheduler(ctx, similarityRepo, time.Hour, 50)

	r := chi.NewRouter()
	for _, mw := range httpx.Middlewares() {
		r.Use(mw)
	}

	// Serve static files for product images
	workDir, _ := os.Getwd()
	filesDir := http.Dir(filepath.Join(workDir, "uploads"))
	FileServer(r, "/uploads", filesDir)

	r.Get("/healthz", func(w http.ResponseWriter, _ *http.Request) { w.Write([]byte("ok")) })

	// PayOS return/cancel static pages
	r.Get("/payos/return", func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r, "payos_return.html")
	})
	r.Get("/payos/cancel", func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r, "payos_cancel.html")
	})

	// Force swagger spec URL to be relative (prevents Swagger UI from generating http:// requests behind proxies)
	r.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("/swagger/doc.json"),
	))

	api := chi.NewRouter()
	authm.RegisterRoutes(api, cfg, gdb, blacklistRepo, userStatusChecker)
	profilem.RegisterRoutes(api, cfg, gdb, blacklistRepo, userStatusChecker)
	catalogm.RegisterRoutes(api, cfg, gdb, blacklistRepo, userStatusChecker) // Register catalog routes
	cartm.RegisterRoutes(api, cfg, gdb, blacklistRepo, userStatusChecker)    // Register cart routes
	addressm.RegisterRoutes(api, cfg, gdb, blacklistRepo, userStatusChecker) // Register address routes

	// Notification module
	notificationSvc := notificationm.RegisterRoutes(api, gdb, cfg.JWT_Secret, blacklistRepo, userStatusChecker)

	// Promotion module
	promoService := promotionm.RegisterRoutes(api, cfg, gdb, blacklistRepo, notificationSvc, userStatusChecker) // Register promotion routes
	promoAdapter := promoRepos.NewPromotionServiceAdapter(promoService)
	orderm.RegisterRoutes(api, gdb, cfg.JWT_Secret, blacklistRepo, promoAdapter, notificationSvc, userStatusChecker) // Register order routes
	adminm.RegisterRoutes(api, gdb, cfg.JWT_Secret, blacklistRepo, userStatusChecker)
	paymentm.RegisterRoutes(api, cfg, gdb, blacklistRepo, userStatusChecker)
	r.Mount("/api/v1", api)

	log.Printf("listening on :%s", cfg.Port)
	log.Fatal(http.ListenAndServe(":"+cfg.Port, r))
}

func runMigrations(db *gorm.DB) {
	if err := authm.Migrate(db); err != nil {
		log.Fatal(err)
	}
	if err := profilem.Migrate(db); err != nil {
		log.Fatal(err)
	}
	if err := catalogm.Migrate(db); err != nil {
		log.Fatal(err)
	}
	if err := cartm.Migrate(db); err != nil {
		log.Fatal(err)
	}
	if err := addressm.Migrate(db); err != nil {
		log.Fatal(err)
	}
	if err := orderm.Migrate(db); err != nil {
		log.Fatal(err)
	}
	if err := notificationm.Migrate(db); err != nil {
		log.Fatal(err)
	}
	if err := paymentm.Migrate(db); err != nil {
		log.Fatal(err)
	}
	if err := promotionm.Migrate(db); err != nil {
		log.Fatal(err)
	}
}

// FileServer conveniently sets up a http.FileServer handler to serve
// static files from a http.FileSystem.
func FileServer(r chi.Router, path string, root http.FileSystem) {
	if strings.ContainsAny(path, ":*") {
		panic("FileServer does not permit URL parameters.")
	}

	if path != "/" && path[len(path)-1] != '/' {
		r.Get(path, http.RedirectHandler(path+"/", 301).ServeHTTP)
		path += "/"
	}
	path += "*"

	r.Get(path, func(w http.ResponseWriter, r *http.Request) {
		rctx := chi.RouteContext(r.Context())
		pathPrefix := strings.TrimSuffix(rctx.RoutePattern(), "*")
		fs := http.StripPrefix(pathPrefix, http.FileServer(root))
		fs.ServeHTTP(w, r)
	})
}
