name: Deploy Admin Web to GitHub Pages

on:
  push:
    branches:
      - ui_mobile # Nhánh chứa code nguồn của bạn

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build Web Admin
        # Đã sửa --base-href theo tên repo của bạn
        run: |
          flutter build web -t lib/main_admin.dart \
          --release \
          --base-href "/FashionApp/" \
          --dart-define=FLAVOR=admin \
          --no-tree-shake-icons

      - name: Fix 404 for GitHub Pages
        # Giúp tránh lỗi 404 khi người dùng tải lại trang (F5)
        run: cp build/web/index.html build/web/404.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages